name: Setup
description: Initializes GitHub Actions runner
runs:
  using: composite
  steps:
    - name: Set Up NodeJS
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 14
    - name: Install Node Modules
      run: yarn install --immutable --immutable-cache
      shell: sh
